[package]
name = "rdma-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
sideway = "0.4.3"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
postcard = { version = "1.1", features = ["alloc"] }
quanta = "0.12.6"
byte-unit = "5.2.6"
clap = { version = "4.6.7", features = ["derive"] }
anyhow = "1.0.104"